### PR TITLE
feat(manual-cookies): Allow input with "Cookie: " prefix

### PR DESCRIPTION
**Pull request by haslersn**

### CODE REVIEW

**Comment by haslersn** [comment]
Note: The core before didn't work. I pushed a n update. Can someone confirm this works?

**Review by iamnotturner — APPROVED** [review]

**Comment by haslersn** [comment]
I tested it and it does work.

Context: when copying the Cookie from firefox, it is prefixed by "Cookie: ".

**Comment by haslersn** [comment]
Update: It seems there was a typo. Instead of `optional_prefix = "Cookie: "`, we merged `optional_prefix = "Cookies: "` (plural). However, I tested it and it does work when inputting a manual cookie prefixed by "Cookie: ". It seems that the web server simply does not care that the cookie string is somewhat malformed.

**Comment by iamnotturner** [comment]
Another (maybe safer/easier) option would be splitting the input string by " " or ": " and using the last element in the list

**Comment by haslersn** [comment]
Splitting by `" "` will not work, because the cookie string can (and will) contain whitespace. Splitting by `": "` also does not necessarily work, because cookie values can contain the following characters AFAIK:

```
!#$%&'()*+-./:<=>?@[]^_`{|}~
```

**Comment by iamnotturner** [comment]
yeah you're right, I was wrong and only thought about inputting just `bm_sz=...`.
Maybe we still should consider that Chrome has `Cookie` as prefix. An option still might be split by " " and concatenating every string in that list with `" ".join(splitted_cookies[1:])` except the first element?

**Comment by haslersn** [comment]
I think #86 is ok for now.

**Pull request merged**
