### PR TITLE
Added Icon

### PR DESCRIPTION
**Pull request by Floskinner**
Hey
wie schon mal erwähnt, habe ich ein eigen erstelltes Icon erstellt und es in die windows-terminservice.spec mit aufgenommen. Könnt ihr euch ja mal überlegen. Falls ihr noch was ändern/anpassen möchtet nur her damit :)

So würde es dann ausschauen: 
icon

### CODE REVIEW

**Comment by haslersn** [comment]
Why are there so many files changed? Did you accidentally use `git add -A` instead of only adding the relevent parts (e.g. interactively via `git add -A --patch`).

**Comment by haslersn** [comment]
The problem seems to be that you also named your branch `beta`, so the workflow also runs on your repository. I think you should create a new branch with only the relevant changes (`README.md`, `images/spritze.ico`, `specs/windows-terminservice.spec`) and create a new PR from it.

There's also a security reason why the maintainers should not merge this PR with all the binaries changed: Otherwise anybody could create a PR to inject malware.

**Comment by Floskinner** [comment]
dammed... well first time of a Pull Request. I close this and open a other one :)

**Comment by iamnotturner** [comment]
Don't worry! :-)

**Pull request closed without merging**
