### PR TITLE
restruct-code -> beta

### PR DESCRIPTION
**Pull request by JuliusJacobitz**

### CODE REVIEW

**Comment by haslersn** [comment]
Your branch does not contain facb7fa34926b960a17bf6005a73ea056eefb8b6. That's probably one reason why there's a merge conflict.

**Comment by haslersn** [comment]
If you merge #104, then the conflict here should be gone.

**Comment by JuliusJacobitz** [comment]
Thank you! but fixed with 37d48a14e8fb69315c149c15f9a0adf80178e037

**Comment by haslersn** [comment]
It's hard to track changes if you push directly to beta instead of creating a PR.

**Pull request closed without merging**
